services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hospital_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hospital_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped