import React, { useState, useEffect } from 'react';
import { FileText, Download, Eye, Plus, CheckCircle, Printer } from 'lucide-react';
import { healthApi } from '../services/api';
import { Modal } from '../components/Modal';

export const ReportsPage = () => {
  const [reports, setReports] = useState([]);
  const [previewReport, setPreviewReport] = useState(null);
  const [downloadSuccess, setDownloadSuccess] = useState('');

  useEffect(() => {
    healthApi.getReports().then(setReports);
  }, []);

  const handleDownload = (report) => {
    setDownloadSuccess(`Downloading ${report.title} (${report.file_format})...`);
    setTimeout(() => setDownloadSuccess(''), 3500);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="glass-card p-6 rounded-3xl border border-slate-700/80 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-white tracking-tight">Clinical Audit & PDF Export Center</h1>
          <p className="text-xs text-slate-400">Generate, preview, and download hospital 30-day readmission audit reports.</p>
        </div>

        <button
          onClick={() => handleDownload({ title: 'New Hospital Cohort Audit', file_format: 'PDF' })}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-medical-cyan to-medical-teal text-slate-950 font-bold text-xs shadow-cyan-glow hover:opacity-90 transition-opacity"
        >
          <Plus className="w-4 h-4" />
          <span>Generate New Audit PDF</span>
        </button>
      </div>

      {downloadSuccess && (
        <div className="p-4 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-400 text-xs font-bold flex items-center gap-2">
          <CheckCircle className="w-5 h-5" />
          <span>{downloadSuccess}</span>
        </div>
      )}

      {/* Reports Table */}
      <div className="glass-card rounded-2xl border border-slate-800 overflow-hidden">
        <table className="w-full text-left text-xs text-slate-300">
          <thead className="bg-navy-900/80 text-slate-400 uppercase text-[10px] tracking-wider border-b border-slate-800">
            <tr>
              <th className="py-3.5 px-4">Report Title</th>
              <th className="py-3.5 px-4">Type</th>
              <th className="py-3.5 px-4">Department</th>
              <th className="py-3.5 px-4">Generated By</th>
              <th className="py-3.5 px-4">Date</th>
              <th className="py-3.5 px-4 text-center">Format</th>
              <th className="py-3.5 px-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60">
            {reports.map((report) => (
              <tr key={report.id} className="hover:bg-slate-800/40 transition-colors">
                <td className="py-3.5 px-4 font-bold text-white flex items-center gap-2.5">
                  <FileText className="w-4 h-4 text-medical-cyan" />
                  <span>{report.title}</span>
                </td>
                <td className="py-3.5 px-4 text-slate-400">{report.report_type}</td>
                <td className="py-3.5 px-4">{report.department}</td>
                <td className="py-3.5 px-4 text-slate-400">{report.generated_by}</td>
                <td className="py-3.5 px-4">{report.date}</td>
                <td className="py-3.5 px-4 text-center">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                    report.file_format === 'PDF' ? 'bg-rose-500/20 text-rose-400' : 'bg-emerald-500/20 text-emerald-400'
                  }`}>
                    {report.file_format}
                  </span>
                </td>
                <td className="py-3.5 px-4 text-right space-x-2">
                  <button
                    onClick={() => setPreviewReport(report)}
                    className="p-1.5 rounded bg-navy-800 text-slate-300 hover:text-white transition-colors"
                    title="Preview Layout"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleDownload(report)}
                    className="p-1.5 rounded bg-navy-800 text-medical-cyan hover:bg-medical-cyan hover:text-slate-950 transition-all"
                    title="Download File"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* PDF Print Preview Modal */}
      {previewReport && (
        <Modal
          isOpen={!!previewReport}
          onClose={() => setPreviewReport(null)}
          title={`PDF Document Preview: ${previewReport.title}`}
          maxWidth="max-w-3xl"
        >
          <div className="bg-white text-slate-900 p-8 rounded-xl space-y-6 shadow-2xl font-serif">
            <div className="flex items-center justify-between border-b border-slate-300 pb-4">
              <div>
                <h2 className="text-xl font-bold text-slate-950 tracking-tight">MetroHealth General Hospital</h2>
                <p className="text-xs text-slate-600 font-sans">Division of Clinical Analytics & AI Quality Governance</p>
              </div>
              <div className="text-right text-xs font-sans text-slate-500">
                <p className="font-bold text-slate-800">{previewReport.date}</p>
                <p>Doc Ref: #AUDIT-2026-904</p>
              </div>
            </div>

            <div className="space-y-3 font-sans">
              <h3 className="text-base font-bold text-slate-900">{previewReport.title}</h3>
              <p className="text-xs text-slate-700 leading-relaxed">
                This document synthesizes 30-day hospital readmission predictive modeling data for {previewReport.department}. All risk scores are calculated using the validated RandomForest Classifier (ROC-AUC 0.914).
              </p>
            </div>

            <div className="border border-slate-300 rounded-lg p-4 font-sans text-xs space-y-2 bg-slate-50">
              <p className="font-bold text-slate-800">Executive Cohort Summary:</p>
              <div className="grid grid-cols-3 gap-2 text-[11px] text-slate-600">
                <div>Total Inpatient Cohort: <strong>148</strong></div>
                <div>High-Risk Flagged: <strong>28</strong></div>
                <div>Target Reduction: <strong>34.2%</strong></div>
              </div>
            </div>

            <div className="pt-6 border-t border-slate-300 flex items-center justify-between font-sans text-xs">
              <span className="text-slate-500">Authorized by: {previewReport.generated_by}</span>
              <button
                onClick={() => window.print()}
                className="flex items-center gap-1 px-3 py-1.5 rounded bg-slate-900 text-white font-bold hover:bg-slate-800"
              >
                <Printer className="w-4 h-4" />
                <span>Print Document</span>
              </button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
};
