import { useEffect, useState } from "react";
import MainLayout from "../layouts/MainLayout";
import api from "../api/api";
import {
  FlaskConical,
  Users,
  AlertTriangle,
  Brain,
  RefreshCw,
} from "lucide-react";

function Research() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const loadResearch = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await api.get(
        "/research/summary"
      );

      setData(response.data);
    } catch (err) {
      setError(
        err.response?.data?.detail ||
          "Unable to load research data."
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadResearch();
  }, []);

  return (
    <MainLayout>
      <div className="flex items-center justify-between mb-8">
        <div>
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-xl bg-purple-100 dark:bg-purple-900/30">
              <FlaskConical className="text-purple-600" />
            </div>

            <div>
              <h1 className="text-3xl font-bold text-slate-800 dark:text-white">
                Research
              </h1>

              <p className="text-gray-500 dark:text-gray-400 mt-1">
                Research and population-level health analysis
              </p>
            </div>
          </div>
        </div>

        <button
          onClick={loadResearch}
          className="flex items-center gap-2 px-4 py-2.5 rounded-lg border dark:border-slate-600 dark:text-white"
        >
          <RefreshCw size={17} />
          Refresh
        </button>
      </div>

      {error && (
        <div className="mb-6 p-4 rounded-xl bg-red-50 text-red-600">
          {error}
        </div>
      )}

      <div className="grid md:grid-cols-3 gap-6">

        <Card
          icon={<Users />}
          title="Total Patients"
          value={loading ? "..." : data?.total_patients}
        />

        <Card
          icon={<AlertTriangle />}
          title="High Risk Patients"
          value={
            loading
              ? "..."
              : data?.high_risk_patients
          }
        />

        <Card
          icon={<Brain />}
          title="Total Predictions"
          value={
            loading
              ? "..."
              : data?.total_predictions
          }
        />

      </div>

      <div className="mt-6 bg-white dark:bg-slate-800 rounded-xl shadow-sm p-6">
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white">
          Average Readmission Risk
        </h2>

        <p className="text-gray-500 dark:text-gray-400 mt-1">
          Average probability generated by the ML prediction system
        </p>

        <div className="mt-6 text-4xl font-bold text-blue-600">
          {loading
            ? "..."
            : `${Math.round(
                (data?.average_risk_score || 0) * 100
              )}%`}
        </div>
      </div>
    </MainLayout>
  );
}

function Card({ icon, title, value }) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm p-6">
      <div className="flex items-center gap-4">
        <div className="p-3 rounded-lg bg-blue-100 dark:bg-blue-900/30 text-blue-600">
          {icon}
        </div>

        <div>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            {title}
          </p>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white">
            {value}
          </h2>
        </div>
      </div>
    </div>
  );
}

export default Research;